[toolchain]
channel = "nightly"
components = [ "rust-src", "rust-analyzer" ]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "wasm32-unknown-unknown"
]
profile = "default"